// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jahnklalgnspbttbippf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphaG5rbGFsZ25zcGJ0dGJpcHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTc2MjcsImV4cCI6MjA2NTQ5MzYyN30.vf-CHPui45M469dAYM4AAsuxVsyjLOk1nFESELTePoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);